export type Specialization = "Criminal" | "Civil" | "Family" | "Corporate" | "Cyber" | "Property" | "Labor" | "Consumer" | "Women Rights";
export type City = "Delhi" | "Mumbai" | "Bengaluru" | "Chennai" | "Hyderabad" | "Pune" | "Jaipur" | "Kochi" | "Ahmedabad" | "Kolkata";
export type ConsultationMode = "Online" | "Offline" | "Both";
export type LawyerLanguage = "English" | "Hindi" | "Tamil" | "Telugu" | "Kannada" | "Marathi" | "Urdu" | "Malayalam";

export interface Lawyer {
  id: number;
  name: string;
  specialization: Specialization;
  city: City;
  experience: number;
  rating: number;
  reviewCount: number;
  feeMin: number;
  feeMax: number;
  mode: ConsultationMode;
  languages: LawyerLanguage[];
  phone: string;
  email: string;
  address: string;
  distance: string;
  available: boolean;
  bio: string;
  barCouncil: string;
}

const metroMultiplier = (city: City): number => {
  const metros: City[] = ["Delhi", "Mumbai", "Bengaluru", "Chennai", "Hyderabad"];
  return metros.includes(city) ? 1.4 : 1.0;
};

const baseFees: Record<Specialization, [number, number]> = {
  Criminal:       [2000, 10000],
  Civil:          [1500,  8000],
  Family:         [1000,  5000],
  Corporate:      [5000, 25000],
  Cyber:          [3000, 15000],
  Property:       [2000, 12000],
  Labor:          [1000,  4000],
  Consumer:       [800,   3500],
  "Women Rights": [500,   3000],
};

export function getFeeRange(spec: Specialization, city: City): [number, number] {
  const [min, max] = baseFees[spec];
  const m = metroMultiplier(city);
  return [Math.round(min * m / 100) * 100, Math.round(max * m / 100) * 100];
}

// 45 lawyers — every city has at least 4 lawyers across different specializations
export const lawyers: Lawyer[] = [
  // ── DELHI (6 lawyers) ──────────────────────────────────────────────────────
  { id:1, name:"Adv. Priya Sharma", specialization:"Criminal", city:"Delhi", experience:14, rating:4.8, reviewCount:312, feeMin:2800, feeMax:14000, mode:"Both", languages:["English","Hindi"], phone:"+91 98765 43210", email:"priya.sharma@legalbot.demo", address:"Chamber 12, Tis Hazari Courts, Delhi", distance:"1.2 km", available:true, bio:"Senior criminal lawyer with 14 years in Delhi High Court. Specialises in bail, trial advocacy, and white-collar crime.", barCouncil:"D/1234/2010" },
  { id:2, name:"Adv. Sunita Verma", specialization:"Family", city:"Delhi", experience:8, rating:4.5, reviewCount:156, feeMin:1400, feeMax:7000, mode:"Online", languages:["English","Hindi"], phone:"+91 98112 34567", email:"sunita.verma@legalbot.demo", address:"Saket District Court, Delhi", distance:"2.8 km", available:true, bio:"Family law specialist focusing on divorce mediation, child custody, and maintenance cases.", barCouncil:"D/5678/2016" },
  { id:3, name:"Adv. Deepak Malhotra", specialization:"Property", city:"Delhi", experience:17, rating:4.7, reviewCount:289, feeMin:2800, feeMax:16800, mode:"Both", languages:["English","Hindi"], phone:"+91 98001 11222", email:"deepak.malhotra@legalbot.demo", address:"Patiala House Courts, New Delhi", distance:"2.0 km", available:true, bio:"Property law expert handling land acquisition, RERA disputes, and real estate transactions across Delhi NCR.", barCouncil:"D/9012/2007" },
  { id:4, name:"Adv. Neha Gupta", specialization:"Consumer", city:"Delhi", experience:6, rating:4.4, reviewCount:98, feeMin:1100, feeMax:4900, mode:"Online", languages:["English","Hindi"], phone:"+91 99100 22333", email:"neha.gupta@legalbot.demo", address:"District Consumer Forum, Rohini, Delhi", distance:"3.5 km", available:true, bio:"Consumer rights advocate with expertise in e-commerce disputes, product liability, and service deficiency cases.", barCouncil:"D/3456/2018" },
  { id:5, name:"Adv. Rahul Saxena", specialization:"Corporate", city:"Delhi", experience:20, rating:4.9, reviewCount:401, feeMin:7000, feeMax:35000, mode:"Both", languages:["English","Hindi"], phone:"+91 98200 33444", email:"rahul.saxena@legalbot.demo", address:"Connaught Place Legal Hub, New Delhi", distance:"1.5 km", available:true, bio:"Top corporate lawyer handling M&A, SEBI compliance, startup advisory, and commercial contracts.", barCouncil:"D/7890/2004" },
  { id:6, name:"Adv. Kavita Rao", specialization:"Cyber", city:"Delhi", experience:9, rating:4.6, reviewCount:167, feeMin:4200, feeMax:21000, mode:"Online", languages:["English","Hindi"], phone:"+91 97300 44555", email:"kavita.rao@legalbot.demo", address:"Cyber Cell Legal Office, Dwarka, Delhi", distance:"4.0 km", available:true, bio:"Cyber law specialist handling online fraud, data privacy breaches, IT Act offences, and digital evidence.", barCouncil:"D/2345/2015" },
  // ── MUMBAI (5 lawyers) ─────────────────────────────────────────────────────
  { id:7, name:"Adv. Rajesh Kumar", specialization:"Family", city:"Mumbai", experience:9, rating:4.6, reviewCount:198, feeMin:1400, feeMax:7000, mode:"Both", languages:["English","Hindi","Marathi"], phone:"+91 87654 32109", email:"rajesh.kumar@legalbot.demo", address:"Bandra Family Court Complex, Mumbai", distance:"2.5 km", available:true, bio:"Compassionate family lawyer handling divorce, custody, and matrimonial disputes with focus on amicable resolution.", barCouncil:"M/5678/2015" },
  { id:8, name:"Adv. Fatima Khan", specialization:"Civil", city:"Mumbai", experience:12, rating:4.6, reviewCount:203, feeMin:2100, feeMax:11200, mode:"Both", languages:["English","Hindi","Urdu"], phone:"+91 91234 56789", email:"fatima.khan@legalbot.demo", address:"City Civil Court, Fort, Mumbai", distance:"2.0 km", available:true, bio:"Civil litigation expert handling property disputes, injunctions, and recovery suits in Bombay High Court.", barCouncil:"M/4567/2012" },
  { id:9, name:"Adv. Sanjay Mehta", specialization:"Property", city:"Mumbai", experience:22, rating:4.8, reviewCount:356, feeMin:2800, feeMax:16800, mode:"Offline", languages:["English","Hindi","Marathi"], phone:"+91 98765 11111", email:"sanjay.mehta@legalbot.demo", address:"Bandra Kurla Complex, Mumbai", distance:"3.2 km", available:true, bio:"Property law veteran with 22 years handling RERA disputes, land acquisition, and real estate transactions in Maharashtra.", barCouncil:"M/1234/2002" },
  { id:10, name:"Adv. Pooja Nair", specialization:"Criminal", city:"Mumbai", experience:11, rating:4.5, reviewCount:221, feeMin:2800, feeMax:14000, mode:"Both", languages:["English","Hindi","Marathi"], phone:"+91 98765 22222", email:"pooja.nair@legalbot.demo", address:"Sessions Court, Mumbai", distance:"1.8 km", available:true, bio:"Criminal defence lawyer with expertise in bail applications, trial advocacy, and appeals in Bombay High Court.", barCouncil:"M/6789/2013" },
  { id:11, name:"Adv. Amit Joshi", specialization:"Labor", city:"Mumbai", experience:13, rating:4.5, reviewCount:145, feeMin:1400, feeMax:5600, mode:"Both", languages:["English","Hindi","Marathi"], phone:"+91 98765 33333", email:"amit.joshi@legalbot.demo", address:"Labour Court, Byculla, Mumbai", distance:"2.9 km", available:true, bio:"Labor law advocate specialising in wrongful termination, PF disputes, and industrial relations in Maharashtra.", barCouncil:"M/3456/2011" },
  // ── BENGALURU (6 lawyers) ──────────────────────────────────────────────────
  { id:12, name:"Adv. Anita Desai", specialization:"Cyber", city:"Bengaluru", experience:7, rating:4.5, reviewCount:134, feeMin:4200, feeMax:21000, mode:"Online", languages:["English","Kannada","Hindi"], phone:"+91 54321 09876", email:"anita.desai@legalbot.demo", address:"Tech Park Legal Hub, Whitefield, Bengaluru", distance:"1.8 km", available:true, bio:"Cyber law specialist with expertise in data privacy, online fraud, IT Act cases, and digital evidence.", barCouncil:"KA/7890/2017" },
  { id:13, name:"Adv. Ravi Shankar", specialization:"Criminal", city:"Bengaluru", experience:18, rating:4.7, reviewCount:334, feeMin:2800, feeMax:14000, mode:"Offline", languages:["English","Kannada","Telugu"], phone:"+91 80 2345 6789", email:"ravi.shankar@legalbot.demo", address:"High Court Building, Bengaluru", distance:"3.5 km", available:true, bio:"Senior criminal advocate with extensive experience in Karnataka High Court. Handles bail, appeals, and trial matters.", barCouncil:"KA/8901/2006" },
  { id:14, name:"Adv. Divya Krishnamurthy", specialization:"Property", city:"Bengaluru", experience:15, rating:4.8, reviewCount:298, feeMin:2800, feeMax:16800, mode:"Both", languages:["English","Kannada","Tamil"], phone:"+91 80 3456 7890", email:"divya.k@legalbot.demo", address:"City Civil Court, Bengaluru", distance:"2.2 km", available:true, bio:"Property law expert handling RERA disputes, land acquisition, and real estate transactions across Karnataka.", barCouncil:"KA/2345/2009" },
  { id:15, name:"Adv. Suresh Gowda", specialization:"Family", city:"Bengaluru", experience:10, rating:4.6, reviewCount:187, feeMin:1400, feeMax:7000, mode:"Both", languages:["English","Kannada","Hindi"], phone:"+91 80 4567 8901", email:"suresh.gowda@legalbot.demo", address:"Family Court, Bengaluru", distance:"1.5 km", available:true, bio:"Family law specialist handling divorce, custody, maintenance, and matrimonial property disputes in Karnataka.", barCouncil:"KA/5678/2014" },
  { id:16, name:"Adv. Meghana Rao", specialization:"Consumer", city:"Bengaluru", experience:5, rating:4.3, reviewCount:76, feeMin:1100, feeMax:4900, mode:"Online", languages:["English","Kannada"], phone:"+91 80 5678 9012", email:"meghana.rao@legalbot.demo", address:"Consumer Forum, Shivajinagar, Bengaluru", distance:"2.8 km", available:true, bio:"Consumer rights advocate handling e-commerce disputes, product defects, and service deficiency cases.", barCouncil:"KA/9012/2019" },
  { id:17, name:"Adv. Kiran Hegde", specialization:"Labor", city:"Bengaluru", experience:12, rating:4.5, reviewCount:143, feeMin:1400, feeMax:5600, mode:"Both", languages:["English","Kannada","Hindi"], phone:"+91 80 6789 0123", email:"kiran.hegde@legalbot.demo", address:"Labour Court, Shivajinagar, Bengaluru", distance:"3.0 km", available:true, bio:"Labor law advocate specialising in IT sector employment disputes, wrongful termination, and PF matters.", barCouncil:"KA/3456/2012" },
  // ── CHENNAI (4 lawyers) ────────────────────────────────────────────────────
  { id:18, name:"Adv. Meena Iyer", specialization:"Consumer", city:"Chennai", experience:16, rating:4.9, reviewCount:445, feeMin:1100, feeMax:4900, mode:"Online", languages:["English","Tamil"], phone:"+91 76543 21098", email:"meena.iyer@legalbot.demo", address:"Consumer Forum Road, Egmore, Chennai", distance:"0.8 km", available:true, bio:"Consumer rights champion with 16 years of experience. Has won over 400 consumer forum cases across Tamil Nadu.", barCouncil:"TN/9012/2008" },
  { id:19, name:"Adv. Senthil Kumar", specialization:"Property", city:"Chennai", experience:19, rating:4.7, reviewCount:312, feeMin:2800, feeMax:16800, mode:"Both", languages:["English","Tamil"], phone:"+91 44 2345 6789", email:"senthil.k@legalbot.demo", address:"City Civil Court, Chennai", distance:"1.5 km", available:true, bio:"Property law expert handling land disputes, RERA complaints, and real estate transactions across Tamil Nadu.", barCouncil:"TN/1234/2005" },
  { id:20, name:"Adv. Preethi Rajan", specialization:"Family", city:"Chennai", experience:8, rating:4.5, reviewCount:134, feeMin:1400, feeMax:7000, mode:"Both", languages:["English","Tamil"], phone:"+91 44 3456 7890", email:"preethi.r@legalbot.demo", address:"Family Court, Egmore, Chennai", distance:"2.0 km", available:true, bio:"Family law specialist handling divorce, custody, and matrimonial disputes in Tamil Nadu courts.", barCouncil:"TN/5678/2016" },
  { id:21, name:"Adv. Balaji Venkatesh", specialization:"Criminal", city:"Chennai", experience:14, rating:4.6, reviewCount:267, feeMin:2800, feeMax:14000, mode:"Offline", languages:["English","Tamil","Telugu"], phone:"+91 44 4567 8901", email:"balaji.v@legalbot.demo", address:"Madras High Court, Chennai", distance:"1.2 km", available:true, bio:"Criminal defence lawyer with extensive experience in Madras High Court. Handles bail, appeals, and trial matters.", barCouncil:"TN/3456/2010" },
  // ── HYDERABAD (4 lawyers) ──────────────────────────────────────────────────
  { id:22, name:"Adv. Arjun Reddy", specialization:"Corporate", city:"Hyderabad", experience:26, rating:4.8, reviewCount:389, feeMin:7000, feeMax:35000, mode:"Both", languages:["English","Telugu","Hindi"], phone:"+91 21098 76543", email:"arjun.reddy@legalbot.demo", address:"HITEC City Legal Tower, Hyderabad", distance:"5.0 km", available:true, bio:"Top corporate lawyer handling M&A, contracts, SEBI compliance, and startup legal advisory.", barCouncil:"TS/1234/1998" },
  { id:23, name:"Adv. Mohammed Iqbal", specialization:"Property", city:"Hyderabad", experience:15, rating:4.6, reviewCount:278, feeMin:2800, feeMax:16800, mode:"Both", languages:["English","Telugu","Urdu","Hindi"], phone:"+91 40 2345 6789", email:"m.iqbal@legalbot.demo", address:"Nampally Court Complex, Hyderabad", distance:"1.5 km", available:true, bio:"Property law expert with deep knowledge of Telangana land laws, RERA, and real estate disputes.", barCouncil:"TS/3456/2009" },
  { id:24, name:"Adv. Sridevi Naidu", specialization:"Family", city:"Hyderabad", experience:11, rating:4.5, reviewCount:189, feeMin:1400, feeMax:7000, mode:"Both", languages:["English","Telugu","Hindi"], phone:"+91 40 3456 7890", email:"sridevi.n@legalbot.demo", address:"Family Court, Secunderabad, Hyderabad", distance:"2.3 km", available:true, bio:"Family law specialist handling divorce, custody, and matrimonial disputes in Telangana courts.", barCouncil:"TS/5678/2013" },
  { id:25, name:"Adv. Venkat Prasad", specialization:"Criminal", city:"Hyderabad", experience:16, rating:4.7, reviewCount:298, feeMin:2800, feeMax:14000, mode:"Offline", languages:["English","Telugu"], phone:"+91 40 4567 8901", email:"venkat.p@legalbot.demo", address:"Telangana High Court, Hyderabad", distance:"3.0 km", available:true, bio:"Criminal defence lawyer with extensive experience in Telangana High Court. Handles bail, appeals, and trial matters.", barCouncil:"TS/7890/2008" },
  // ── PUNE (4 lawyers) ───────────────────────────────────────────────────────
  { id:26, name:"Adv. Sneha Kulkarni", specialization:"Property", city:"Pune", experience:12, rating:4.6, reviewCount:198, feeMin:2000, feeMax:12000, mode:"Both", languages:["English","Hindi","Marathi"], phone:"+91 20 2345 6789", email:"sneha.k@legalbot.demo", address:"District Court, Shivajinagar, Pune", distance:"1.8 km", available:true, bio:"Property law expert handling RERA disputes, land acquisition, and real estate transactions across Maharashtra.", barCouncil:"MH/1234/2012" },
  { id:27, name:"Adv. Rohit Deshpande", specialization:"Corporate", city:"Pune", experience:14, rating:4.7, reviewCount:234, feeMin:5000, feeMax:25000, mode:"Both", languages:["English","Hindi","Marathi"], phone:"+91 20 3456 7890", email:"rohit.d@legalbot.demo", address:"Hinjewadi IT Park Legal Hub, Pune", distance:"4.5 km", available:true, bio:"Corporate lawyer specialising in startup advisory, commercial contracts, and IT sector legal compliance.", barCouncil:"MH/5678/2010" },
  { id:28, name:"Adv. Anjali Patil", specialization:"Family", city:"Pune", experience:7, rating:4.4, reviewCount:112, feeMin:1000, feeMax:5000, mode:"Online", languages:["English","Hindi","Marathi"], phone:"+91 20 4567 8901", email:"anjali.p@legalbot.demo", address:"Family Court, Pune", distance:"2.2 km", available:true, bio:"Family law specialist handling divorce, custody, and maintenance cases in Pune courts.", barCouncil:"MH/9012/2017" },
  { id:29, name:"Adv. Nikhil Bhosale", specialization:"Labor", city:"Pune", experience:9, rating:4.4, reviewCount:89, feeMin:1000, feeMax:4000, mode:"Both", languages:["English","Hindi","Marathi"], phone:"+91 20 5678 9012", email:"nikhil.b@legalbot.demo", address:"Labour Court, Pune", distance:"3.1 km", available:true, bio:"Labor law advocate specialising in wrongful termination, PF disputes, and industrial relations in Pune.", barCouncil:"MH/3456/2015" },
  // ── JAIPUR (3 lawyers) ─────────────────────────────────────────────────────
  { id:30, name:"Adv. Vikram Singh", specialization:"Labor", city:"Jaipur", experience:11, rating:4.4, reviewCount:89, feeMin:1000, feeMax:4000, mode:"Both", languages:["English","Hindi"], phone:"+91 43210 98765", email:"vikram.singh@legalbot.demo", address:"Labour Court Complex, Jaipur", distance:"4.2 km", available:true, bio:"Labor law advocate specialising in wrongful termination, PF disputes, and industrial relations.", barCouncil:"RJ/2345/2013" },
  { id:31, name:"Adv. Geeta Sharma", specialization:"Property", city:"Jaipur", experience:13, rating:4.5, reviewCount:167, feeMin:2000, feeMax:12000, mode:"Both", languages:["English","Hindi"], phone:"+91 141 2345 678", email:"geeta.s@legalbot.demo", address:"High Court, Jaipur", distance:"2.5 km", available:true, bio:"Property law expert handling land disputes, RERA complaints, and real estate transactions across Rajasthan.", barCouncil:"RJ/5678/2011" },
  { id:32, name:"Adv. Anil Mathur", specialization:"Criminal", city:"Jaipur", experience:16, rating:4.6, reviewCount:234, feeMin:2000, feeMax:10000, mode:"Offline", languages:["English","Hindi"], phone:"+91 141 3456 789", email:"anil.m@legalbot.demo", address:"Sessions Court, Jaipur", distance:"1.8 km", available:true, bio:"Criminal defence lawyer with extensive experience in Rajasthan High Court. Handles bail, appeals, and trial matters.", barCouncil:"RJ/9012/2008" },
  // ── KOCHI (3 lawyers) ──────────────────────────────────────────────────────
  { id:33, name:"Adv. Lakshmi Nair", specialization:"Women Rights", city:"Kochi", experience:19, rating:4.9, reviewCount:521, feeMin:500, feeMax:3000, mode:"Both", languages:["English","Malayalam","Tamil"], phone:"+91 32109 87654", email:"lakshmi.nair@legalbot.demo", address:"Women Legal Aid Centre, MG Road, Kochi", distance:"0.5 km", available:true, bio:"Dedicated women rights lawyer providing free/subsidised legal aid. Expert in DV Act, POSH, and matrimonial laws.", barCouncil:"KL/6789/2005" },
  { id:34, name:"Adv. Thomas Varghese", specialization:"Property", city:"Kochi", experience:17, rating:4.7, reviewCount:289, feeMin:2000, feeMax:12000, mode:"Both", languages:["English","Malayalam"], phone:"+91 484 2345 678", email:"thomas.v@legalbot.demo", address:"High Court of Kerala, Ernakulam", distance:"1.2 km", available:true, bio:"Property law expert handling land disputes, RERA complaints, and real estate transactions across Kerala.", barCouncil:"KL/1234/2007" },
  { id:35, name:"Adv. Sindhu Menon", specialization:"Family", city:"Kochi", experience:8, rating:4.5, reviewCount:134, feeMin:1000, feeMax:5000, mode:"Online", languages:["English","Malayalam"], phone:"+91 484 3456 789", email:"sindhu.m@legalbot.demo", address:"Family Court, Ernakulam, Kochi", distance:"2.0 km", available:true, bio:"Family law specialist handling divorce, custody, and matrimonial disputes in Kerala courts.", barCouncil:"KL/5678/2016" },
  // ── AHMEDABAD (3 lawyers) ──────────────────────────────────────────────────
  { id:36, name:"Adv. Suresh Patel", specialization:"Property", city:"Ahmedabad", experience:21, rating:4.7, reviewCount:267, feeMin:2000, feeMax:12000, mode:"Offline", languages:["English","Hindi","Marathi"], phone:"+91 65432 10987", email:"suresh.patel@legalbot.demo", address:"Law Chambers, CG Road, Ahmedabad", distance:"3.1 km", available:true, bio:"Property law expert handling land disputes, RERA complaints, and real estate transactions across Gujarat.", barCouncil:"GJ/3456/2003" },
  { id:37, name:"Adv. Hetal Shah", specialization:"Corporate", city:"Ahmedabad", experience:15, rating:4.6, reviewCount:198, feeMin:5000, feeMax:25000, mode:"Both", languages:["English","Hindi","Marathi"], phone:"+91 79 2345 6789", email:"hetal.s@legalbot.demo", address:"SG Highway Legal Hub, Ahmedabad", distance:"4.0 km", available:true, bio:"Corporate lawyer specialising in commercial contracts, startup advisory, and business compliance in Gujarat.", barCouncil:"GJ/7890/2009" },
  { id:38, name:"Adv. Bhavna Trivedi", specialization:"Consumer", city:"Ahmedabad", experience:9, rating:4.4, reviewCount:112, feeMin:800, feeMax:3500, mode:"Online", languages:["English","Hindi"], phone:"+91 79 3456 7890", email:"bhavna.t@legalbot.demo", address:"Consumer Forum, Navrangpura, Ahmedabad", distance:"2.5 km", available:true, bio:"Consumer rights advocate handling product defects, service deficiency, and e-commerce disputes in Gujarat.", barCouncil:"GJ/2345/2015" },
  // ── KOLKATA (4 lawyers) ────────────────────────────────────────────────────
  { id:39, name:"Adv. Subhash Banerjee", specialization:"Criminal", city:"Kolkata", experience:22, rating:4.8, reviewCount:378, feeMin:2000, feeMax:10000, mode:"Both", languages:["English","Hindi"], phone:"+91 33 2345 6789", email:"subhash.b@legalbot.demo", address:"Calcutta High Court, Kolkata", distance:"1.5 km", available:true, bio:"Senior criminal advocate with 22 years in Calcutta High Court. Handles bail, appeals, and complex trial matters.", barCouncil:"WB/1234/2002" },
  { id:40, name:"Adv. Rupa Chatterjee", specialization:"Property", city:"Kolkata", experience:14, rating:4.6, reviewCount:223, feeMin:2000, feeMax:12000, mode:"Both", languages:["English","Hindi"], phone:"+91 33 3456 7890", email:"rupa.c@legalbot.demo", address:"City Civil Court, Kolkata", distance:"2.0 km", available:true, bio:"Property law expert handling land disputes, RERA complaints, and real estate transactions across West Bengal.", barCouncil:"WB/5678/2010" },
  { id:41, name:"Adv. Debashish Roy", specialization:"Labor", city:"Kolkata", experience:16, rating:4.5, reviewCount:189, feeMin:1000, feeMax:4000, mode:"Offline", languages:["English","Hindi"], phone:"+91 33 4567 8901", email:"debashish.r@legalbot.demo", address:"Labour Court, Kolkata", distance:"2.8 km", available:true, bio:"Labor law advocate specialising in wrongful termination, PF disputes, and industrial relations in West Bengal.", barCouncil:"WB/9012/2008" },
  { id:42, name:"Adv. Moumita Das", specialization:"Women Rights", city:"Kolkata", experience:11, rating:4.7, reviewCount:234, feeMin:500, feeMax:3000, mode:"Both", languages:["English","Hindi"], phone:"+91 33 5678 9012", email:"moumita.d@legalbot.demo", address:"Women Legal Aid Centre, Park Street, Kolkata", distance:"1.8 km", available:true, bio:"Women rights lawyer providing legal aid for domestic violence, harassment, and matrimonial disputes.", barCouncil:"WB/3456/2013" },
  // ── CROSS-CITY ONLINE SPECIALISTS ─────────────────────────────────────────
  { id:43, name:"Adv. Pradeep Nambiar", specialization:"Cyber", city:"Bengaluru", experience:10, rating:4.6, reviewCount:178, feeMin:4200, feeMax:21000, mode:"Online", languages:["English","Kannada","Malayalam"], phone:"+91 80 7890 1234", email:"pradeep.n@legalbot.demo", address:"Koramangala Legal Hub, Bengaluru", distance:"2.5 km", available:true, bio:"Cyber law expert handling data breaches, online fraud, social media crimes, and IT Act offences.", barCouncil:"KA/4567/2014" },
  { id:44, name:"Adv. Zara Hussain", specialization:"Civil", city:"Hyderabad", experience:13, rating:4.5, reviewCount:198, feeMin:2100, feeMax:11200, mode:"Both", languages:["English","Telugu","Urdu","Hindi"], phone:"+91 40 5678 9012", email:"zara.h@legalbot.demo", address:"City Civil Court, Hyderabad", distance:"2.2 km", available:true, bio:"Civil litigation expert handling property disputes, injunctions, and recovery suits in Telangana courts.", barCouncil:"TS/6789/2011" },
  { id:45, name:"Adv. Ramesh Iyer", specialization:"Corporate", city:"Chennai", experience:18, rating:4.7, reviewCount:312, feeMin:7000, feeMax:35000, mode:"Both", languages:["English","Tamil"], phone:"+91 44 5678 9012", email:"ramesh.i@legalbot.demo", address:"Anna Salai Legal Tower, Chennai", distance:"1.8 km", available:true, bio:"Corporate lawyer specialising in M&A, commercial contracts, and startup advisory in Tamil Nadu.", barCouncil:"TN/7890/2006" },
  // ── ADDITIONAL LAWYERS — varied fees, experience, specializations ──────────
  // Budget tier (500-1800)
  { id:46, name:"Adv. Ramesh Yadav",      specialization:"Consumer",     city:"Delhi",     experience:2,  rating:4.0, reviewCount:23,  feeMin:500,  feeMax:1500, mode:"Online",  languages:["English","Hindi"],           phone:"+91 98001 55001", email:"ramesh.yadav@legalbot.demo",      address:"Rohini District Court, Delhi",              distance:"5.0 km", available:true,  bio:"Junior consumer rights advocate. Handles small claims, product defects, and e-commerce refund disputes at affordable rates.", barCouncil:"D/0011/2022" },
  { id:47, name:"Adv. Preethi Nair",      specialization:"Labor",        city:"Kochi",     experience:3,  rating:4.1, reviewCount:31,  feeMin:600,  feeMax:1800, mode:"Online",  languages:["English","Malayalam"],       phone:"+91 484 5001 001", email:"preethi.nair@legalbot.demo",     address:"Ernakulam Labour Court, Kochi",             distance:"3.2 km", available:true,  bio:"Early-career labour law advocate helping workers with PF disputes, minimum wage issues, and wrongful termination at low cost.", barCouncil:"KL/0022/2021" },
  { id:48, name:"Adv. Suraj Mehta",       specialization:"Family",       city:"Jaipur",    experience:2,  rating:3.9, reviewCount:18,  feeMin:700,  feeMax:2000, mode:"Online",  languages:["English","Hindi"],           phone:"+91 141 5002 002", email:"suraj.mehta@legalbot.demo",      address:"Family Court, Jaipur",                      distance:"2.1 km", available:true,  bio:"New family law practitioner handling divorce paperwork, maintenance applications, and mutual consent cases at budget rates.", barCouncil:"RJ/0033/2023" },
  { id:49, name:"Adv. Divya Pillai",      specialization:"Consumer",     city:"Chennai",   experience:3,  rating:4.2, reviewCount:42,  feeMin:800,  feeMax:2200, mode:"Online",  languages:["English","Tamil"],           phone:"+91 44 5003 003", email:"divya.pillai@legalbot.demo",      address:"Consumer Forum, Anna Nagar, Chennai",       distance:"4.0 km", available:true,  bio:"Consumer protection specialist for Tamil Nadu. Handles defective goods, insurance claims, and service complaints affordably.", barCouncil:"TN/0044/2021" },
  { id:50, name:"Adv. Karan Bhatt",       specialization:"Labor",        city:"Ahmedabad", experience:4,  rating:4.1, reviewCount:55,  feeMin:900,  feeMax:2500, mode:"Both",    languages:["English","Hindi","Marathi"], phone:"+91 79 5004 004", email:"karan.bhatt@legalbot.demo",       address:"Labour Court, Navrangpura, Ahmedabad",      distance:"2.8 km", available:true,  bio:"Labour law advocate specialising in factory worker rights, ESI disputes, and contract labour issues across Gujarat.", barCouncil:"GJ/0055/2020" },
  // Mid tier (1500-6000)
  { id:51, name:"Adv. Nandita Roy",       specialization:"Women Rights",  city:"Kolkata",   experience:7,  rating:4.5, reviewCount:112, feeMin:1500, feeMax:4000, mode:"Both",    languages:["English","Hindi"],           phone:"+91 33 5005 005", email:"nandita.roy@legalbot.demo",       address:"Women Legal Aid Centre, Salt Lake, Kolkata",distance:"2.5 km", available:true,  bio:"Women rights advocate handling domestic violence, POSH complaints, and matrimonial disputes with compassion and expertise.", barCouncil:"WB/0066/2017" },
  { id:52, name:"Adv. Aakash Tiwari",     specialization:"Criminal",     city:"Pune",      experience:6,  rating:4.3, reviewCount:89,  feeMin:1800, feeMax:5000, mode:"Offline", languages:["English","Hindi","Marathi"], phone:"+91 20 5006 006", email:"aakash.tiwari@legalbot.demo",     address:"Sessions Court, Shivajinagar, Pune",        distance:"1.9 km", available:true,  bio:"Criminal defence lawyer handling bail applications, FIR quashing, and trial matters in Pune and Pimpri-Chinchwad courts.", barCouncil:"MH/0077/2018" },
  { id:53, name:"Adv. Shalini Menon",     specialization:"Civil",        city:"Bengaluru", experience:8,  rating:4.4, reviewCount:134, feeMin:2000, feeMax:6000, mode:"Both",    languages:["English","Kannada"],         phone:"+91 80 5007 007", email:"shalini.menon@legalbot.demo",     address:"City Civil Court, Bengaluru",               distance:"2.3 km", available:true,  bio:"Civil litigation specialist handling injunctions, recovery suits, and property disputes in Karnataka courts.", barCouncil:"KA/0088/2016" },
  { id:54, name:"Adv. Farhan Qureshi",    specialization:"Property",     city:"Mumbai",    experience:10, rating:4.6, reviewCount:178, feeMin:2500, feeMax:7000, mode:"Both",    languages:["English","Hindi","Urdu"],    phone:"+91 22 5008 008", email:"farhan.qureshi@legalbot.demo",    address:"Bandra Kurla Complex, Mumbai",              distance:"3.5 km", available:true,  bio:"Property law expert handling RERA complaints, builder disputes, and real estate transactions across Maharashtra.", barCouncil:"M/0099/2014" },
  { id:55, name:"Adv. Geetha Krishnan",   specialization:"Family",       city:"Chennai",   experience:9,  rating:4.5, reviewCount:145, feeMin:2200, feeMax:6500, mode:"Both",    languages:["English","Tamil"],           phone:"+91 44 5009 009", email:"geetha.krishnan@legalbot.demo",   address:"Family Court, Egmore, Chennai",             distance:"1.8 km", available:true,  bio:"Family law specialist with expertise in divorce, child custody, and matrimonial property disputes in Tamil Nadu.", barCouncil:"TN/0100/2015" },
  // Upper-mid tier (4000-15000)
  { id:56, name:"Adv. Nitin Agarwal",     specialization:"Corporate",    city:"Pune",      experience:15, rating:4.7, reviewCount:234, feeMin:4500, feeMax:18000, mode:"Both",   languages:["English","Hindi","Marathi"], phone:"+91 20 5010 010", email:"nitin.agarwal@legalbot.demo",     address:"Hinjewadi IT Park, Pune",                   distance:"6.0 km", available:true,  bio:"Corporate lawyer specialising in startup legal advisory, term sheets, shareholder agreements, and SEBI compliance.", barCouncil:"MH/0111/2009" },
  { id:57, name:"Adv. Poornima Iyer",     specialization:"Cyber",        city:"Chennai",   experience:11, rating:4.6, reviewCount:189, feeMin:5000, feeMax:20000, mode:"Online",  languages:["English","Tamil"],           phone:"+91 44 5011 011", email:"poornima.iyer@legalbot.demo",     address:"Anna Salai Legal Hub, Chennai",             distance:"2.2 km", available:true,  bio:"Cyber law expert handling data breaches, IT Act offences, social media crimes, and digital evidence in Tamil Nadu.", barCouncil:"TN/0122/2013" },
  { id:58, name:"Adv. Sameer Joshi",      specialization:"Criminal",     city:"Hyderabad", experience:13, rating:4.7, reviewCount:267, feeMin:4000, feeMax:15000, mode:"Offline", languages:["English","Telugu","Hindi"],  phone:"+91 40 5012 012", email:"sameer.joshi@legalbot.demo",      address:"Nampally Court Complex, Hyderabad",         distance:"2.0 km", available:true,  bio:"Criminal advocate with extensive experience in Telangana High Court. Handles bail, appeals, and complex trial matters.", barCouncil:"TS/0133/2011" },
  { id:59, name:"Adv. Rekha Pillai",      specialization:"Civil",        city:"Kochi",     experience:12, rating:4.5, reviewCount:156, feeMin:3500, feeMax:12000, mode:"Both",    languages:["English","Malayalam"],       phone:"+91 484 5013 013", email:"rekha.pillai@legalbot.demo",     address:"High Court of Kerala, Ernakulam",           distance:"1.5 km", available:true,  bio:"Civil litigation expert handling property disputes, injunctions, and recovery suits in Kerala courts.", barCouncil:"KL/0144/2012" },
  { id:60, name:"Adv. Vivek Sharma",      specialization:"Labor",        city:"Delhi",     experience:16, rating:4.8, reviewCount:312, feeMin:4500, feeMax:16000, mode:"Both",    languages:["English","Hindi"],           phone:"+91 98765 60001", email:"vivek.sharma@legalbot.demo",      address:"Labour Court, Kasturba Gandhi Marg, Delhi", distance:"2.5 km", available:true,  bio:"Senior labour law advocate with 16 years handling industrial disputes, retrenchment cases, and PF litigation.", barCouncil:"D/0155/2008" },
  // Premium tier (8000-75000)
  { id:61, name:"Adv. Krishnamurthy S.",  specialization:"Corporate",    city:"Chennai",   experience:28, rating:4.9, reviewCount:512, feeMin:10000,feeMax:50000, mode:"Both",   languages:["English","Tamil"],           phone:"+91 44 5015 015", email:"krishnamurthy@legalbot.demo",     address:"Anna Salai Legal Tower, Chennai",           distance:"1.2 km", available:true,  bio:"Senior corporate counsel with 28 years. Handles M&A, IPO advisory, SEBI matters, and high-value commercial disputes.", barCouncil:"TN/0166/1996" },
  { id:62, name:"Adv. Meenakshi Reddy",   specialization:"Criminal",     city:"Hyderabad", experience:24, rating:4.9, reviewCount:445, feeMin:8000, feeMax:40000, mode:"Both",   languages:["English","Telugu"],          phone:"+91 40 5016 016", email:"meenakshi.reddy@legalbot.demo",   address:"Telangana High Court, Hyderabad",           distance:"1.8 km", available:false, bio:"Top criminal advocate in Telangana. Handles high-profile cases, bail in Supreme Court, and complex criminal appeals.", barCouncil:"TS/0177/2000" },
  { id:63, name:"Adv. Subramaniam P.",    specialization:"Property",     city:"Chennai",   experience:22, rating:4.8, reviewCount:389, feeMin:7000, feeMax:35000, mode:"Offline", languages:["English","Tamil"],           phone:"+91 44 5017 017", email:"subramaniam.p@legalbot.demo",     address:"Madras High Court, Chennai",                distance:"0.8 km", available:true,  bio:"Property law veteran with 22 years. Handles land acquisition, RERA, and high-value real estate disputes in Tamil Nadu.", barCouncil:"TN/0188/2002" },
  { id:64, name:"Adv. Harish Chandra",    specialization:"Corporate",    city:"Delhi",     experience:30, rating:5.0, reviewCount:678, feeMin:15000,feeMax:75000, mode:"Both",   languages:["English","Hindi"],           phone:"+91 98765 64001", email:"harish.chandra@legalbot.demo",    address:"Supreme Court of India, New Delhi",         distance:"3.0 km", available:false, bio:"Supreme Court advocate with 30 years. Handles constitutional matters, high-value corporate disputes, and PIL cases.", barCouncil:"D/0199/1994" },
  { id:65, name:"Adv. Nalini Krishnan",   specialization:"Cyber",        city:"Bengaluru", experience:18, rating:4.8, reviewCount:334, feeMin:8000, feeMax:35000, mode:"Online",  languages:["English","Kannada","Tamil"], phone:"+91 80 5019 019", email:"nalini.krishnan@legalbot.demo",   address:"UB City Legal Hub, Bengaluru",              distance:"3.8 km", available:true,  bio:"Senior cyber law expert handling data protection, DPDP Act compliance, and major online fraud cases across India.", barCouncil:"KA/0200/2006" },
];

export const cities: City[] = ["Delhi","Mumbai","Bengaluru","Chennai","Hyderabad","Pune","Jaipur","Kochi","Ahmedabad","Kolkata"];
export const specializations: Specialization[] = ["Criminal","Civil","Family","Corporate","Cyber","Property","Labor","Consumer","Women Rights"];

